export type BabyName = {
  name: string;
  etimology: string;
};

export let babyNames: BabyName[] = [
  {
    name: "Sophia",
    etimology: `Means "wisdom" in Greek. This was the name of an early, probably mythical, saint who died of grief after her three daughters were martyred during the reign of the emperor Hadrian. Legends about her probably arose as a result of a medieval misunderstanding of the phrase Hagia Sophia "Holy Wisdom", which is the name of a large basilica in Constantinople.`,
  },
  {
    name: "Jackson",
    etimology: `From an English surname meaning "son of Jack". A famous bearer of the surname was American president Andrew Jackson (1767-1845).`,
  },
  { name: "Olivia", etimology: "" },
  { name: "Liam", etimology: "" },
  { name: "Emma", etimology: "" },
  { name: "Noah", etimology: "" },
  { name: "Ava", etimology: "" },
  { name: "Lucas", etimology: "" },
  { name: "Isabella", etimology: "" },
  { name: "Oliver", etimology: "" },
  { name: "Mia", etimology: "" },
  { name: "Ethan", etimology: "" },
  { name: "Amelia", etimology: "" },
  { name: "Aiden", etimology: "" },
  { name: "Harper", etimology: "" },
  { name: "Elijah", etimology: "" },
  { name: "Evelyn", etimology: "" },
  { name: "James", etimology: "" },
  { name: "Charlotte", etimology: "" },
  { name: "Benjamin", etimology: "" },
  { name: "Abigail", etimology: "" },
  { name: "William", etimology: "" },
  { name: "Emily", etimology: "" },
  { name: "Alexander", etimology: "" },
  { name: "Madison", etimology: "" },
  { name: "Michael", etimology: "" },
  { name: "Elizabeth", etimology: "" },
  { name: "Mason", etimology: "" },
  { name: "Sofia", etimology: "" },
  { name: "Logan", etimology: "" },
  { name: "Avery", etimology: "" },
  { name: "Matthew", etimology: "" },
  { name: "Ella", etimology: "" },
  { name: "Daniel", etimology: "" },
  { name: "Scarlett", etimology: "" },
  { name: "Henry", etimology: "" },
  { name: "Grace", etimology: "" },
  { name: "Joseph", etimology: "" },
  { name: "Lily", etimology: "" },
  { name: "Samuel", etimology: "" },
  { name: "Chloe", etimology: "" },
  { name: "David", etimology: "" },
  { name: "Victoria", etimology: "" },
  { name: "Carter", etimology: "" },
  { name: "Riley", etimology: "" },
  { name: "Wyatt", etimology: "" },
  { name: "Aria", etimology: "" },
  { name: "Jayden", etimology: "" },
  { name: "Zoey", etimology: "" },
  { name: "Gabriel", etimology: "" },
];
